<!DOCTYPE html>

<html>
    
    <form method="post" action="index.phtml">
        <label for="color-select">Choose a color:</label>

        <select name="color-select" id="color-select">
            <option value="blue">Blue</option>
            <option value="red">Red</option>
            <option value="black">Black</option>
        </select>
        <input type="submit" value="Send" />
    </form>

    
</html>