<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password</title>
</head>
<body>
    <form action="decrypt_password.phtml" method="post">
        <label for="password">Password :</label>
        <input type="text" id="password" name="password" required>
        <label for="hash_password">Hash password :</label>
        <input type="text" id="hash_password" name="hash_password" required>
        <input type="submit" value="Send">
    </form>
</body>
</html>